config-version: 2

name: 'stripe_metrics'
version: '0.1.1'

require-dbt-version: [">=1.0.0", "<2.0.0"]

models:
  stripe_metrics:
    +materialized: table

vars:
  stripe_metrics:
    balance_transaction: "{{ ref('stg_stripe__balance_transaction') }}"
    card: "{{ ref('stg_stripe__card') }}"
    charge: "{{ ref('stg_stripe__charge') }}"
    customer: "{{ ref('stg_stripe__customer') }}"
    fee: "{{ ref('stg_stripe__fee') }}"
    invoice: "{{ ref('stg_stripe__invoice') }}"
    invoice_line_item: "{{ ref('stg_stripe__invoice_line_item') }}"
    payment_intent: "{{ ref('stg_stripe__payment_intent') }}"
    payment_method_card: "{{ ref('stg_stripe__payment_method_card') }}"
    payment_method: "{{ ref('stg_stripe__payment_method') }}"
    payout: "{{ ref('stg_stripe__payout') }}"
    plan: "{{ ref('stg_stripe__plan') }}"
    refund: "{{ ref('stg_stripe__refund') }}"
    subscription: "{{ ref('stg_stripe__subscription') }}"

  stripe_source:
    stripe__subscription_history: true
