version: 2

models:
  - name: stripe__monthly_bookings
    description: "Monthly revenue from all transactions."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_bookings
        description: ""

  - name: stripe__monthly_churned_customer_revenue
    description: "Monthly revenue lost due to churned customers."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_churned_customer_revenue
        description: ""

  - name: stripe__monthly_churned_customers
    description: "Monthly count of customers that churned."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_churned_customers
        description: ""

  - name: stripe__monthly_customer_revenue
    description: "Customer wise revenue for each month ranging from 2010-01-31 to 2030-12-31"
    columns:
      - name: date_month
        description: ""
      - name: revenue_starting_date
        description: ""
      - name: revenue_ending_date
        description: ""
      - name: customer_id
        description: ""
      - name: current_month_revenue
        description: ""
      - name: revenue_till_previous_month
        description: ""
      - name: previous_month_revenue
        description: ""
      - name: current_annual_recurring_revenue
        description: ""

  - name: stripe__main_transactions
    description: "Stripe transactions enriched with subscription, customer, invoice details and other relevant data."
    columns:
      - name: subscription_id
        description: ""
      - name: customer_id
        description: ""
      - name: customer_description
        description: ""
      - name: customer_email
        description: ""
      - name: subscription_status
        description: ""
      - name: billing
        description: ""
      - name: billing_cycle_anchor
        description: ""
      - name: subscription_created_at
        description: ""
      - name: subscription_cancel_at
        description: ""
      - name: subscription_canceled_at
        description: ""
      - name: subscription_ended_at
        description: ""
      - name: current_period_start
        description: ""
      - name: current_period_end
        description: ""
      - name: invoice_id
        description: ""
      - name: invoice_created_at
        description: ""
      - name: invoice_status
        description: ""
      - name: min_line_item_period_start
        description: ""
      - name: max_line_item_period_end
        description: ""
      - name: invoice_period
        description: ""
      - name: balance_transaction_id
        description: ""
      - name: created_at
        description: ""
      - name: available_on
        description: ""
      - name: currency
        description: ""
      - name: balance_transaction_description
        description: ""
      - name: balance_transaction_amount
        description: ""
      - name: refund_amount
        description: ""
      - name: balance_transaction_fee
        description: ""
      - name: balance_transaction_net
        description: ""
      - name: balance_transaction_type
        description: ""
      - name: refund_metadata
        description: ""

  - name: stripe__mrr
    description: "Monthly recurring revenue."
    columns:
      - name: period
        description: ""
      - name: stripe__mrr
        description: ""
      - name: roll_avg_quarter
        description: ""

  - name: stripe__mrr_main_transactions
    description: "Model derived from stripe__main_transactions used for calculating Monthly Recurring Revenue metric"
    columns:
      - name: subscription_id
        description: ""
      - name: customer_id
        description: ""
      - name: customer_description
        description: ""
      - name: customer_email
        description: ""
      - name: subscription_status
        description: ""
      - name: billing
        description: ""
      - name: billing_cycle_anchor
        description: ""
      - name: subscription_created_at
        description: ""
      - name: subscription_cancel_at
        description: ""
      - name: subscription_canceled_at
        description: ""
      - name: subscription_ended_at
        description: ""
      - name: current_period_start
        description: ""
      - name: current_period_end
        description: ""
      - name: invoice_id
        description: ""
      - name: invoice_created_at
        description: ""
      - name: invoice_status
        description: ""
      - name: min_line_item_period_start
        description: ""
      - name: max_line_item_period_end
        description: ""
      - name: invoice_period
        description: ""
      - name: balance_transaction_id
        description: ""
      - name: created_at
        description: ""
      - name: available_on
        description: ""
      - name: currency
        description: ""
      - name: balance_transaction_description
        description: ""
      - name: balance_transaction_amount
        description: ""
      - name: refund_amount
        description: ""
      - name: balance_transaction_fee
        description: ""
      - name: balance_transaction_net
        description: ""
      - name: balance_transaction_type
        description: ""
      - name: refund_metadata
        description: ""
      - name: monthly_revenue
        description: ""
      - name: revenue_starting_date
        description: ""
      - name: revenue_ending_date
        description: ""

  - name: stripe__monthly_new_customer_revenue
    description: "Monthly revenue due to customers that signed up for the first time."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_new_customer_revenue
        description: ""

  - name: stripe__monthly_new_customers
    description: "Monthly count of customers that signed up for the first time."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_new_customers
        description: ""

  - name: stripe__monthly_platform_fees
    description: "Monthly fees paid to Stripe."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_platform_fees
        description: ""

  - name: stripe__monthly_recovered_customer_revenue
    description: "Monthly revenue due recovery of previously churned customers."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_recovered_customer_revenue
        description: ""

  - name: stripe__monthly_recovered_customers
    description: "Monthly number of previously churned customers who signed up again."
    columns:
      - name: period
        description: ""
      - name: stripe__monthly_recovered_customers
        description: ""
